language: c
sudo: required
services:
  - docker

## We build on as many OCaml version as we can support. These versions
## are in fact tags for the ocaml/opam2 Docker image that we pull.

env:
  global:
    - "WHY3COMMIT=#41d0c60df"
  matrix:
    # - TAG=4.05
    # - TAG=4.06
    - TAG=4.07

## Two steps: we first build the Dockerfile. If it succeeds, we try
## running tests, installing and uninstalling in the Dockerfile.

script:
  - docker build --build-arg TAG=$TAG --build-arg SWITCH=$SWITCH --build-arg WHY3COMMIT=$WHY3COMMIT --tag colisanr/colis-language:$TRAVIS_BRANCH .
